#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DBSPACE=/opt/usr/dbspace
APPS_DIR=/opt/usr/apps
SHARE_DIR=/opt/usr/share

chown 5000:5000 /opt/home/app
find /opt/home/app -print0 | xargs -0 chsmack -a 'system::homedir'
find /opt/home/app -type d -print0 | xargs -0 chsmack -t

if [ ! -e /opt/home/app/.e ]; then
	mkdir -p /opt/home/app/.e
fi
find /opt/home/app/.e -print0 | xargs -0 chsmack -a 'e17::config'
find /opt/home/app/.e -type d -print0 | xargs -0 chsmack -t

# set vconf label when first boot
#if [ ! -e /opt/etc/.vconf_labeling ]; then
#	chsmack -a 'system::vconf' /opt/var/kdb/db
#	chsmack -t /opt/var/kdb/db
#	find /opt/var/kdb/db -print0 | xargs -0 chsmack -a 'system::vconf'
#	find /opt/var/kdb/db -type d -print0 | xargs -0 chsmack -t
#	find /opt/var/kdb/file -print0 | xargs -0 chsmack -a 'system::vconf'
#	find /opt/var/kdb/file -type d -print0 | xargs -0 chsmack -t
#	find /var/run/memory -print0 | xargs -0 chsmack -a 'system::vconf'
#	find /var/run/memory -type d -print0 | xargs -0 chsmack -t
#	touch /opt/etc/.vconf_labeling
#fi

# Set device node permissions for security
#chsmack -a 'system::camera' /dev/video1
#chsmack -a 'system::camera' /dev/s3c-jpg
#chsmack -a 'system::app_logging' /dev/log_main
#chsmack -a 'system::app_logging' /dev/log_events
#chsmack -a 'system::app_logging' /dev/log_radio
#chsmack -a 'system::sys_logging' /dev/log_system
#chsmack -a 'system::audio' /dev/snd/
#chsmack -a 'system::audio' /dev/snd/controlC0
#chsmack -a 'system::audio' /dev/snd/pcmC0D0p
#chsmack -a 'system::audio' /dev/snd/pcmC0D1p
#chsmack -a 'system::audio' /dev/snd/pcmC0D2p
#chsmack -a 'system::audio' /dev/snd/pcmC0D3p
#chsmack -a 'system::audio' /dev/snd/timer
#chsmack -a 'system::recording' /dev/snd/pcmC0D0c
#chsmack -a 'system::recording' /dev/snd/pcmC0D1c
#chsmack -a 'system::recording' /dev/snd/pcmC0D2c
#chsmack -a 'system::recording' /dev/snd/pcmC0D3c
#chsmack -a 'system::hwcodec' /dev/s3c-mfc
#chsmack -a 'system::hwcodec' /dev/video5
#chsmack -a 'system::hwcodec' /dev/video6
#chsmack -a 'system::video' /dev/fb0
#chsmack -a 'system::video' /dev/video0
#chsmack -a 'system::video' /dev/video2
#chsmack -a 'system::video' /dev/video3
#chsmack -a 'system::video' /dev/s3c-mem
#chsmack -a 'system::radio' /dev/radio0
#chsmack -a 'system::system_bklight' /sys/class/backlight/*/brightness
#chsmack -a 'system::system_torch' /sys/class/leds/leds-torch/brightness

echo "0.0.0.0/1 system::use_internet" >> /smack/netlabel
echo "128.0.0.0/1 system::use_internet" >> /smack/netlabel
echo "127.0.0.1 -CIPSO" >> /smack/netlabel
echo "192.168.129.1 @" >> /smack/netlabel
echo "192.168.129.3/32 @" >> /smack/netlabel
echo "system::use_internet" > /smack/ambient

find /opt/usr/media -print0 | xargs -0 chsmack -a 'system::media'
find /opt/usr/media -type d -print0 | xargs -0 chsmack -t
